environment:
  - PORT=3000
services:
  web:
    domain: ${HOST}
    build: .
    ports: 
      - 3000
      - 3002
balancers:
  ingress:
    annotations:
    - test.annotation.org/value=foobar
    service: web
    ports:
      5000: 3001
      3002: 3002
      3000:
        protocol: TCP
        port: 3000
