environment:
  - PORT=3000
services:
  web:
    domain: ${HOST}
    build: .
    port: 3000
balancers:
  ingress:
    annotations:
    - test.annotation.org/value=foobar
    service: web
    port: 7000
    ports:
      3000:
        protocol: UDP
        port: 1000
      4000:
        protocol: UDP
        port: 1001
      5000:
        protocol: UDP
        port: 1002
